apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatnoir-log-pvc
  labels:
    app: chatnoir-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: ceph-rbd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatnoir-web
  labels:
    app: chatnoir-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatnoir-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chatnoir-web
    spec:
      volumes:
        # Requires pre-deployed config maps
        - name: config
          configMap:
            name: chatnoir-config
        - name: warmer
          configMap:
            name: chatnoir-warmer-script

        - name: log-volume
          persistentVolumeClaim:
            claimName: chatnoir-log-pvc
        - name: tmp-volume
          emptyDir:
            medium: Memory
        - name: aol-log
          hostPath:
            path: /mnt/ceph/storage/corpora/corpora-webis/corpus-webis-aol-long-queries-14
            type: Directory
      securityContext:
        fsGroup: 1000
      containers:
        - name: chatnoir-web
          image: webis/chatnoir-web:latest
          ports:
            - name: tomcat
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/chatnoir2/config.yml
              name: config
              subPath: config.yml
            - mountPath: /var/log/chatnoir2
              name: log-volume
            - mountPath: /tmp
              name: tmp-volume
        - name: index-warmer
          image: alpine:latest
          volumeMounts:
            - mountPath: /usr/local/bin/warmer
              name: warmer
              subPath: warmer.sh
            - mountPath: /query-log
              name: aol-log
          command: ["/bin/sh"]
          args: ["-c", "apk add --no-cache bash python3 curl && exec bash /usr/local/bin/warmer"]

